# # .github/workflows/python-test.yml

# name: Run Python Tests

# # This action runs on two triggers:
# # 1. When you push code to the 'main' branch
# # 2. When you create a Pull Request
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest  # Use a standard Linux machine

#     steps:
#     - name: Check out repository code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.11' # You can change this to your Python version

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirement.txt
#         pip install pytest  # Install pytest for the runner

#     - name: Run tests with pytest
#       run: |
#         pytest


# .github/workflows/python-test.yml

name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        pip install pytest

    - name: Run tests with pytest
      # This 'env:' block is the new part you must add
      env:
        COMPOSIO_API_KEY: ${{ secrets.COMPOSIO_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest